services:
  - type: worker
    name: sportwetten-telegram-bot
    runtime: python
    repo: https://github.com/SirinBaba92/sportwetten-analyse
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8523388781:AAFdmnGPRKsInqCID65CER1NhuXOgQ9qjzU
      - key: API_URL
        value: https://sportwetten-analyse-v4-9.streamlit.app
      - key: PYTHON_VERSION
        value: 3.11.0
